version: "2.1"

services:

  voidmart:
    build: .
    privileged: true
    network_mode: host
    ports:
      - '8080'
    volumes:
      - 'cache:/cache'
    labels:
      io.balena.features.supervisor-api: '1'

  browser:
    image: bh.cr/balenalabs/browser-amd64
    privileged: true
    network_mode: host
    ports:
      - '5011'
      - '35173'
    volumes:
      - 'browser:/data'

  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.firmware: "1"

volumes:
  pwc:
  browser:
  cache:
